export const ALL_CURRENCIES = [
  { code: "USD", symbol: "$" },
  { code: "EUR", symbol: "€" },
  { code: "GBP", symbol: "£" },
  { code: "INR", symbol: "₹" },
  { code: "AED", symbol: "د.إ" },
  { code: "AUD", symbol: "A$" },
  { code: "CAD", symbol: "C$" },
  { code: "SGD", symbol: "S$" },
  { code: "CHF", symbol: "CHF" },
  { code: "MYR", symbol: "RM" },
  { code: "JPY", symbol: "¥" },
  { code: "CNY", symbol: "¥" },
  { code: "THB", symbol: "฿" },
  { code: "IDR", symbol: "Rp" },
  { code: "ZAR", symbol: "R" },
  { code: "BRL", symbol: "R$" },
  { code: "MXN", symbol: "$" },
  { code: "RUB", symbol: "₽" },
  { code: "KRW", symbol: "₩" },
  { code: "TRY", symbol: "₺" },
  { code: "SAR", symbol: "ر.س" },
  { code: "SEK", symbol: "kr" },
  { code: "NOK", symbol: "kr" },
  { code: "DKK", symbol: "kr" },
  { code: "PLN", symbol: "zł" },
  { code: "TWD", symbol: "NT$" },
  { code: "VND", symbol: "₫" },
  { code: "PHP", symbol: "₱" },
  { code: "ARS", symbol: "$" },
  { code: "CLP", symbol: "$" },
  { code: "COP", symbol: "$" },
  { code: "EGP", symbol: "E£" },
  { code: "HKD", symbol: "HK$" },
  { code: "NZD", symbol: "NZ$" },
  { code: "PEN", symbol: "S/" },
  { code: "QAR", symbol: "ر.ق" },
  { code: "ILS", symbol: "₪" },
  { code: "BDT", symbol: "৳" },
  { code: "PKR", symbol: "₨" },
  { code: "LKR", symbol: "Rs" },
  { code: "NGN", symbol: "₦" },
  { code: "KES", symbol: "KSh" },
  { code: "GHS", symbol: "GH₵" }
].sort((a, b) => a.code.localeCompare(b.code));

export const getCurrencySymbol = (currency: string) => {
  const found = ALL_CURRENCIES.find(c => c.code === currency);
  return found ? found.symbol : currency;
};
