import React from "react";
import GrainRateCalculator from "./modules/grain/GrainRateCalculator";
import GrainCfsTransport from "./modules/grain/GrainCfsTransport";
import GrainBagPriceAndStock from "./modules/grain/GrainBagPriceAndStock";
import GrainQuoteSheet from "./modules/grain/GrainQuoteSheet";
import SugarRateCalculator from "./modules/sugar/SugarRateCalculator";
import SugarCfsTransport from "./modules/sugar/SugarCfsTransport";
import SugarBagPriceAndStock from "./modules/sugar/SugarBagPriceAndStock";
import SugarQuoteSheet from "./modules/sugar/SugarQuoteSheet";
import VegetablesFruitsRateCalculator from "./modules/vegetables_fruits/VegetablesFruitsRateCalculator";
import VegetablesFruitsCfsTransport from "./modules/vegetables_fruits/VegetablesFruitsCfsTransport";
import VegetablesFruitsBagPriceAndStock from "./modules/vegetables_fruits/VegetablesFruitsBagPriceAndStock";
import VegetablesFruitsQuoteSheet from "./modules/vegetables_fruits/VegetablesFruitsQuoteSheet";
import TilesRateCalculator from "./modules/tiles/TilesRateCalculator";
import TilesCfsTransport from "./modules/tiles/TilesCfsTransport";
import TilesBagPriceAndStock from "./modules/tiles/TilesBagPriceAndStock";
import TilesQuoteSheet from "./modules/tiles/TilesQuoteSheet";
import ChemicalsRateCalculator from "./modules/chemicals/ChemicalsRateCalculator";
import ChemicalsCfsTransport from "./modules/chemicals/ChemicalsCfsTransport";
import ChemicalsBagPriceAndStock from "./modules/chemicals/ChemicalsBagPriceAndStock";
import ChemicalsQuoteSheet from "./modules/chemicals/ChemicalsQuoteSheet";
import SpicesRateCalculator from "./modules/spices/SpicesRateCalculator";
import SpicesCfsTransport from "./modules/spices/SpicesCfsTransport";
import SpicesBagPriceAndStock from "./modules/spices/SpicesBagPriceAndStock";
import SpicesQuoteSheet from "./modules/spices/SpicesQuoteSheet";
import SaltsRateCalculator from "./modules/salts/SaltsRateCalculator";
import SaltsCfsTransport from "./modules/salts/SaltsCfsTransport";
import SaltsBagPriceAndStock from "./modules/salts/SaltsBagPriceAndStock";
import SaltsQuoteSheet from "./modules/salts/SaltsQuoteSheet";
import MetalRateCalculator from "./modules/metal/MetalRateCalculator";
import MetalCfsTransport from "./modules/metal/MetalCfsTransport";
import MetalBagPriceAndStock from "./modules/metal/MetalBagPriceAndStock";
import MetalQuoteSheet from "./modules/metal/MetalQuoteSheet";
import NutsRateCalculator from "./modules/nuts/NutsRateCalculator";
import NutsCfsTransport from "./modules/nuts/NutsCfsTransport";
import NutsBagPriceAndStock from "./modules/nuts/NutsBagPriceAndStock";
import NutsQuoteSheet from "./modules/nuts/NutsQuoteSheet";
import ApparelRateCalculator from "./modules/apparel/ApparelRateCalculator";
import ApparelCfsTransport from "./modules/apparel/ApparelCfsTransport";
import ApparelBagPriceAndStock from "./modules/apparel/ApparelBagPriceAndStock";
import ApparelQuoteSheet from "./modules/apparel/ApparelQuoteSheet";
import PackagingRateCalculator from "./modules/packaging/PackagingRateCalculator";
import PackagingCfsTransport from "./modules/packaging/PackagingCfsTransport";
import PackagingBagPriceAndStock from "./modules/packaging/PackagingBagPriceAndStock";
import PackagingQuoteSheet from "./modules/packaging/PackagingQuoteSheet";
import CoffeeTeaRateCalculator from "./modules/coffee_tea/CoffeeTeaRateCalculator";
import CoffeeTeaCfsTransport from "./modules/coffee_tea/CoffeeTeaCfsTransport";
import CoffeeTeaBagPriceAndStock from "./modules/coffee_tea/CoffeeTeaBagPriceAndStock";
import CoffeeTeaQuoteSheet from "./modules/coffee_tea/CoffeeTeaQuoteSheet";
import CottonYarnRateCalculator from "./modules/cotton_yarn/CottonYarnRateCalculator";
import CottonYarnCfsTransport from "./modules/cotton_yarn/CottonYarnCfsTransport";
import CottonYarnBagPriceAndStock from "./modules/cotton_yarn/CottonYarnBagPriceAndStock";
import CottonYarnQuoteSheet from "./modules/cotton_yarn/CottonYarnQuoteSheet";
import TimberRateCalculator from "./modules/timber/TimberRateCalculator";
import TimberCfsTransport from "./modules/timber/TimberCfsTransport";
import TimberBagPriceAndStock from "./modules/timber/TimberBagPriceAndStock";
import TimberQuoteSheet from "./modules/timber/TimberQuoteSheet";
import AirCargoRateCalculator from "./modules/air_cargo/AirCargoRateCalculator";
import AirCargoCfsTransport from "./modules/air_cargo/AirCargoCfsTransport";
import AirCargoBagPriceAndStock from "./modules/air_cargo/AirCargoBagPriceAndStock";
import AirCargoQuoteSheet from "./modules/air_cargo/AirCargoQuoteSheet";
import PharmaRateCalculator from "./modules/pharma/PharmaRateCalculator";
import PharmaCfsTransport from "./modules/pharma/PharmaCfsTransport";
import PharmaBagPriceAndStock from "./modules/pharma/PharmaBagPriceAndStock";
import PharmaQuoteSheet from "./modules/pharma/PharmaQuoteSheet";
import OilRateCalculator from "./modules/oil/OilRateCalculator";
import OilCfsTransport from "./modules/oil/OilCfsTransport";
import OilBagPriceAndStock from "./modules/oil/OilBagPriceAndStock";
import OilQuoteSheet from "./modules/oil/OilQuoteSheet";
import GenericRateCalculator from "./modules/generic/GenericRateCalculator";
import GenericCfsTransport from "./modules/generic/GenericCfsTransport";
import GenericBagPriceAndStock from "./modules/generic/GenericBagPriceAndStock";
import GenericQuoteSheet from "./modules/generic/GenericQuoteSheet";
import RcnRateCalculator from "./modules/rcn/RcnRateCalculator";
import RcnCfsTransport from "./modules/rcn/RcnCfsTransport";
import RcnBagPriceAndStock from "./modules/rcn/RcnBagPriceAndStock";
import RcnQuoteSheet from "./modules/rcn/RcnQuoteSheet";
import RateCalculator from "./components/RateCalculator";
import CfsTransport from "./components/CfsTransport";
import BagPriceAndStock from "./components/BagPriceAndStock";
import QuoteSheet from "./components/QuoteSheet";

export const getRateCalculator = (ind: string) => {
  if (ind === 'grain' || ind === 'rice_merchant') return GrainRateCalculator;
  if (ind === 'sugar') return SugarRateCalculator;
  if (ind === 'vegetables_fruits') return VegetablesFruitsRateCalculator;
  if (ind === 'tiles') return TilesRateCalculator;
  if (ind === 'chemicals') return ChemicalsRateCalculator;
  if (ind === 'spices') return SpicesRateCalculator;
  if (ind === 'salts') return SaltsRateCalculator;
  if (ind === 'metal') return MetalRateCalculator;
  if (ind === 'nuts') return NutsRateCalculator;
  if (ind === 'apparel') return ApparelRateCalculator;
  if (ind === 'packaging') return PackagingRateCalculator;
  if (ind === 'coffee_tea') return CoffeeTeaRateCalculator;
  if (ind === 'cotton_yarn') return CottonYarnRateCalculator;
  if (ind === 'timber') return TimberRateCalculator;
  if (ind === 'air_cargo') return AirCargoRateCalculator;
  if (ind === 'pharma') return PharmaRateCalculator;
  if (ind === 'oil' || ind === 'petroleum') return OilRateCalculator;
  if (ind === 'generic' || ind === 'agri_multi') return GenericRateCalculator;
    if (ind === 'rcn') return RcnRateCalculator;
  return RateCalculator;
};
export const getCfsTransport = (ind: string) => {
  if (ind === 'grain' || ind === 'rice_merchant') return GrainCfsTransport;
  if (ind === 'sugar') return SugarCfsTransport;
  if (ind === 'vegetables_fruits') return VegetablesFruitsCfsTransport;
  if (ind === 'tiles') return TilesCfsTransport;
  if (ind === 'chemicals') return ChemicalsCfsTransport;
  if (ind === 'spices') return SpicesCfsTransport;
  if (ind === 'salts') return SaltsCfsTransport;
  if (ind === 'metal') return MetalCfsTransport;
  if (ind === 'nuts') return NutsCfsTransport;
  if (ind === 'apparel') return ApparelCfsTransport;
  if (ind === 'packaging') return PackagingCfsTransport;
  if (ind === 'coffee_tea') return CoffeeTeaCfsTransport;
  if (ind === 'cotton_yarn') return CottonYarnCfsTransport;
  if (ind === 'timber') return TimberCfsTransport;
  if (ind === 'air_cargo') return AirCargoCfsTransport;
  if (ind === 'pharma') return PharmaCfsTransport;
  if (ind === 'oil' || ind === 'petroleum') return OilCfsTransport;
  if (ind === 'generic' || ind === 'agri_multi') return GenericCfsTransport;
    if (ind === 'rcn') return RcnCfsTransport;
  return CfsTransport;
};
export const getBagPriceAndStock = (ind: string) => {
  if (ind === 'grain' || ind === 'rice_merchant') return GrainBagPriceAndStock;
  if (ind === 'sugar') return SugarBagPriceAndStock;
  if (ind === 'vegetables_fruits') return VegetablesFruitsBagPriceAndStock;
  if (ind === 'tiles') return TilesBagPriceAndStock;
  if (ind === 'chemicals') return ChemicalsBagPriceAndStock;
  if (ind === 'spices') return SpicesBagPriceAndStock;
  if (ind === 'salts') return SaltsBagPriceAndStock;
  if (ind === 'metal') return MetalBagPriceAndStock;
  if (ind === 'nuts') return NutsBagPriceAndStock;
  if (ind === 'apparel') return ApparelBagPriceAndStock;
  if (ind === 'packaging') return PackagingBagPriceAndStock;
  if (ind === 'coffee_tea') return CoffeeTeaBagPriceAndStock;
  if (ind === 'cotton_yarn') return CottonYarnBagPriceAndStock;
  if (ind === 'timber') return TimberBagPriceAndStock;
  if (ind === 'air_cargo') return AirCargoBagPriceAndStock;
  if (ind === 'pharma') return PharmaBagPriceAndStock;
  if (ind === 'oil' || ind === 'petroleum') return OilBagPriceAndStock;
  if (ind === 'generic' || ind === 'agri_multi') return GenericBagPriceAndStock;
    if (ind === 'rcn') return RcnBagPriceAndStock;
  return BagPriceAndStock;
};
export const getQuoteSheet = (ind: string) => {
  if (ind === 'grain' || ind === 'rice_merchant') return GrainQuoteSheet;
  if (ind === 'sugar') return SugarQuoteSheet;
  if (ind === 'vegetables_fruits') return VegetablesFruitsQuoteSheet;
  if (ind === 'tiles') return TilesQuoteSheet;
  if (ind === 'chemicals') return ChemicalsQuoteSheet;
  if (ind === 'spices') return SpicesQuoteSheet;
  if (ind === 'salts') return SaltsQuoteSheet;
  if (ind === 'metal') return MetalQuoteSheet;
  if (ind === 'nuts') return NutsQuoteSheet;
  if (ind === 'apparel') return ApparelQuoteSheet;
  if (ind === 'packaging') return PackagingQuoteSheet;
  if (ind === 'coffee_tea') return CoffeeTeaQuoteSheet;
  if (ind === 'cotton_yarn') return CottonYarnQuoteSheet;
  if (ind === 'timber') return TimberQuoteSheet;
  if (ind === 'air_cargo') return AirCargoQuoteSheet;
  if (ind === 'pharma') return PharmaQuoteSheet;
  if (ind === 'oil' || ind === 'petroleum') return OilQuoteSheet;
  if (ind === 'generic' || ind === 'agri_multi') return GenericQuoteSheet;
    if (ind === 'rcn') return RcnQuoteSheet;
  return QuoteSheet;
};
